I2c encoder support
KMKfw/kmk_firmware pull request #322
Opened 2022-02-07 19:37 UTC by giovanniborella

This PR adds support for the Adafruit I2C QT Rotary Encoder with NeoPixel break-out board over i2c. 

Only basic functionality like the stock encoder extension:
* invertable
* on_move, on_press keypress.

Still needs work for implementing NeoPixel-capabilities

2022-02-08 00:30 UTC, kdb424 commented
Try running `make fix-formatting fix-isort test` and see if that returns a clean test. We should be able to review once that test passes.

2022-02-08 07:42 UTC, kdb424 commented
isort is still not pleased, and looks like there are some other changes needed. We can get to those after you intend to come out of draft state, but the line I showed before should sort that, and has been tested on Mac and Linux. I'm not sure if anyone has tested Windows.

2022-02-08 07:57 UTC, giovanniborella commented
@kdb424 I'm trying to get make up and running on WSL, will pull out of draft when test is successfull

2022-02-08 08:23 UTC, kdb424 commented
Looks generally great. Don't mind us nitpicking the small details here and there. Thanks so much for adding support for this, and we'll get it merged as soon as we can!

2022-02-08 19:00 UTC, Tonasz commented
A lot of code is duplicated with `encoder.py` file. Most of code could be reused. For example there could be `AbstractEncoder` and inheriting from him `GPIOEncoder` (I don't know what's the right name) and `I2CEncoder` and they would differ only where they need. What do you think about it?
Also, I see that doc example use `from kmk.modules.i2c_encoder import i2cEncoderHandler` but that's `EncoderHandler` in `i2c_encoder.py` file.

2022-02-09 07:38 UTC, giovanniborella commented
Good point @Tonasz! - ill get on merging the two

2022-02-11 22:47 UTC, giovanniborella commented
I dont have a GPIO encoder setup, so i'm afraid that part is untested

2022-02-12 20:47 UTC, Tonasz commented on kmk/modules/encoder.py
> +                self.on_button_do(self.get_state())
```suggestion
        new_button_state = self.pin_button.get_value()
        if new_button_state != self._button_state:
            self._button_state = new_button_state
            if self.on_button_do is not None:
                self.on_button_do(self.get_state())
```

2022-02-12 21:03 UTC, Tonasz requested changes
It looks a lot cleaner now :)
Despite reintroducing 2 small, but already fixed in the past issues, **it looks good to me**.
I don't have I2C encoders to test it. I got one classic encoder on my keyboard and it works fine. Somebody with multiple encoders could confirm it working, but if mentioned issue is fixed, it should be fine.

2022-02-14 22:33 UTC, giovanniborella commented
I merged @Tonasz' suggestions

2022-02-17 01:58 UTC, kdb424 commented
I'll leave the final call to Tonasz before I check for any final merge blockers.

2022-02-19 10:10 UTC, Tonasz approved these changes
I'm not able right now to test how it will behave with multiple encoders (but it should be alright after latest changes) but this looks good to me :) I don't know other I2C encoders and how compatible they are with each other, so if there's gonna be a need, we will have to do some additional changes.

2022-02-20 05:31 UTC, Tonasz approved these changes
LGTM :) (see above comment)

2022-02-20 05:33 UTC, kdb424 approved these changes

2022-02-20 05:33 UTC, merged