Add kmk.scanners.bidirectional
KMKfw/kmk_firmware pull request #346
Opened 2022-03-01 09:44 UTC by s-ol

This is for matrices that use diodes in both directions to double the number of keys without using extra pins.

>     A Scanner for Keyboard Matrices with Diodes in both directions.
>     In a bidirectional matrix, each (col, row) crossing can be used twice -
>     once with a ROW2COL diode ("A"), and once with a COL2ROW diode ("B").
>     The raw key numbers returned by this scanner are based on this layout ("up_down"):
>         C1  C2  C3
>       +-----------
>     R1| A0  A1  A2
>     R2| A3  A4  A5
>       +-----------
>     R1| B6  B7  B8
>     R1| B9 B10 B11

Here's an example schematic that would use the `mapping_left_right` layout:

![image](https://user-images.githubusercontent.com/1731279/156145053-47a5a3d4-3bbf-4bb0-8c71-bb491a5a60fe.png)

2022-03-02 00:24 UTC, xs5871 reviewed
Looks fine so far, but I'll wait until this is out of draft for a proper review.

2022-03-02 00:24 UTC, xs5871 commented on kmk/scanners/bidirectional.py
> +        coord_mapping.extend(ic(y, x, cols) for x in range(cols))
A heads-up:
`intify_coordinate` should be regarded as legacy for backwards compatibility . It's easier to understand what's going on if you do:
```python
coord_mapping = list(range(2*cols*rows))
```

2022-03-19 02:12 UTC, kdb424 commented
@s-ol Curious to if you are continuing to work on this. I'm closing stale issues and PR's, but don't want to close this by mistake if you are intending to continue work on this.

2022-03-19 08:27 UTC, s-ol commented
@kdb424 no worries, I will work on this but I'm still waiting to receive my MCUs unfortunately

2022-03-19 08:28 UTC, kdb424 commented
Fantastic! Glad to hear it's still being worked on. No rush.

2022-04-08 19:37 UTC, xs5871 requested changes
Looks sane to me. I won't build custom hardware specifically to test it, but I trust that it's in the authors own interest that it works.
Use the CP implementation of the KeyEvent and we're good.

2022-04-08 19:37 UTC, xs5871 commented on kmk/scanners/bidirectional.py
> +from kmk.matrix import KeyEvent
```suggestion
from keypad import Event as KeyEvent
```

2022-04-11 07:31 UTC, s-ol commented
Sooo playing around with this a bit I figured out *why* this isn't done more commonly:  
It has ghosting problems. The version of the code here has them already with certain combinations of two keys, but it can be improved by tri-stating the unused output lines while scanning. At that point you have ghosting only with four keys pressed, but it's still unsuitable for my application.

Since my board is probably the only one in existence right now made that way, and soon it won't be anymore, I'll close this PR :wink:

2022-04-11 07:31 UTC, closed without merging