modholdandtap implementation
KMKfw/kmk_firmware pull request #411
Opened 2022-04-22 18:38 UTC by masiullah

This module allows to immitate the behaviour of ATL+TAB or CMD+TAB, etc.  
Basically, it will hold the mod and tap a key on a layer other than default layer. The mod will be released when any other key is pressed or the layer key is released.
The key will do nothing when it is placed on the default layer

Not sure if something like this is already there in KMK

2022-04-23 01:23 UTC, masiullah commented
@kdb424 would you be able to make this a draft PR as I need to do some more testing

2022-04-23 03:00 UTC, masiullah commented
I completed the missing test on the kb2040. Its ready for review

2022-04-24 17:56 UTC, xs5871 commented
I'd like to submit a review, but I honestly don't understand what this does or what it is for.
I read through the code, but I guess missing some context.
@masiullah would you be so kind and expand a little on your explanation, maybe with one or two examples even?

2022-04-24 18:18 UTC, masiullah commented
> I'd like to submit a review, but I honestly don't understand what this does or what it is for. I read through the code, but I guess I'm missing some context. @masiullah would you be so kind and expand a little on your explanation, maybe with one or two examples even?

This key will help to simulate the behavior of alt + tab that is used to switch between apps for smaller keyboards where there are not a lot of keys on the default layer. To make this work put this key in non default layer and then hold the layer key and press the mod hold tap key and it work similar to alt  + tab (like you keep holding the layer key and pressing the mhat key will switch to different windows). Hope this is helpful to get the context

2022-04-24 18:37 UTC, xs5871 commented
What's the difference to `KC.LALT(KC.TAB)` on a second layer?

2022-04-24 19:19 UTC, masiullah commented
> What's the difference to `KC.LALT(KC.TAB)` on a second layer?

I think that does not work like a real atl tab as you cannot hold the alt key and switch between windows. this will allow to do that

2022-04-24 20:05 UTC, xs5871 commented
Thanks, I think I get it now. Is it strictly necessary to restrict that to non-default layers?

2022-04-24 20:19 UTC, masiullah commented
yes, otherwise you will not be able to hold the layer key which will act like a modifier
I was thinking to have it on default layer also but the problem was releasing the modifier and could do using a timeout but thought if some one is going to put the key on the default layer then he must be having a lots of keys and most likely will not use it as he will have dedicated keys for the mods

2022-04-24 20:42 UTC, xs5871 commented
I understand that it's more likely to have this on a secondary layer, but I don't see a reason to disallow it on the default layer.
The logic you use to remove the held modifier checks for any key event, not for a layer transition.

Basically, we're talking about a key with a "personal" sticky modifier, right?

2022-04-24 21:10 UTC, masiullah commented
I think the restriction can be removed and also please let me know if module name or key name should be changed

2022-04-25 13:59 UTC, masiullah commented
@xs5871  its ready for review

2022-04-26 19:25 UTC, xs5871 requested changes
I'd prefer a more intuitive name.
Both "hold" and "tap" already have a meaning, and it refers to typing actions by the user, not something the keyboard does for you. The best I could come up with is "StickyMod", though that may be confused with "OneShot". "StickierMod", "StuckMod", "PermaMod", "TenaciousMod", I'm just exhausting a thesaurus now...

Let's start with the code changes, find a better name, and then we can polish the docs. We'll probably need a couple of rounds of reviews, if that's ok with you.

Edit: sorry, don't know why github doubled every one of my change requests...

2022-04-26 19:25 UTC, xs5871 commented on kmk/modules/modholdandtap.py
> +            validator=ModHoldAndTapValidator,
```suggestion
            validator=ModHoldAndTapMeta,
```

2022-04-26 19:25 UTC, xs5871 commented on kmk/modules/modholdandtap.py
> +            validator=ModHoldAndTapValidator,
```suggestion
            validator=ModHoldAndTapMeta,
```

2022-04-26 19:25 UTC, xs5871 commented on kmk/modules/modholdandtap.py
> +            keyboard.process_key(key.meta.kc, is_pressed)
This should go into `on_pressed` and `on_released` key handlers.

2022-04-26 19:25 UTC, xs5871 commented on kmk/modules/modholdandtap.py
> +        self._prev_key = None
`_active_key` may be more fitting.

2022-04-26 19:25 UTC, xs5871 commented on kmk/modules/modholdandtap.py
> +        self._prev_key = None
`_active_key` may be more fitting.

2022-04-26 19:25 UTC, xs5871 commented on kmk/modules/modholdandtap.py
> +            keyboard.process_key(key.meta.kc, is_pressed)
```suggestion
            if self._active and self._prev_key is not None and is_pressed:
                # release previous key
                self.release(keyboard, self._prev_key)
            self._prev_key = key
            if is_pressed:
                keyboard.process_key(key.meta.mod, is_pressed)

                self._active = True
            keyboard.process_key(key.meta.kc, is_pressed)
```

This should go into `on_pressed` and `on_released` key handlers.

2022-04-26 19:25 UTC, xs5871 commented on kmk/modules/modholdandtap.py
> +            keyboard.process_key(key.meta.kc, is_pressed)
```suggestion
            if self._active and self._prev_key is not None and is_pressed:
                # release previous key
                self.release(keyboard, self._prev_key)
            self._prev_key = key
            if is_pressed:
                keyboard.process_key(key.meta.mod, is_pressed)

                self._active = True
            keyboard.process_key(key.meta.kc, is_pressed)
```

This should go into `on_pressed` and `on_released` key handlers.

2022-04-26 20:11 UTC, masiullah commented
@xs5871  I will go through the review comments and implement the same and multiple rounds of reviews are fine as we want to make it polished and easily used

2022-04-26 20:11 UTC, masiullah commented
@xs5871  I will go through the review comments and implement the same and multiple rounds of reviews are fine as we want to make it polished and easily used

2022-04-28 15:28 UTC, masiullah commented on kmk/modules/modholdandtap.py
> +class ModHoldAndTapValidator:
Changed the name to StickyModMeta

2022-04-29 12:58 UTC, xs5871 commented on docs/sticky_mod.md
> +The mod will be on hold and the key will be tapped. The mod will be released when any other key is pressed or the layer key is released.
```suggestion
This module allows to hold a modifier while a key is being tapped repeatedly; the modifier will be released when any other key is pressed or released.
This is for example useful if you want to switch between open windows with ALT+TAB or CMD+TAB, using only a single key.
```
```suggestion
This module allows to immitate the behaviour of ATL+TAB or CMD+TAB, etc. for switching between open windows.
The mod will be on hold and the key will be tapped. The mod will be released when any other key is pressed or the layer key is released.
```

2022-04-29 12:58 UTC, xs5871 commented on kmk/modules/sticky_mod.py
> +            if self._active_key is not None:
Is `self._active` even necessary when `self._current_key is not None` has the same effect?

2022-04-29 12:58 UTC, xs5871 commented on kmk/modules/sticky_mod.py
> +            if self._active_key is not None:
Is `self._active` even necessary when `self._current_key is not None` has the same effect?

2022-04-30 10:42 UTC, xs5871 approved these changes
I' happy with that.

2022-05-02 21:02 UTC, merged