Make things easier to setup
KMKfw/kmk_firmware pull request #460
Opened 2022-06-04 21:36 UTC by crazyiop

A few small things I changed who helped me to setup my keyboard. I guess it might help others.

2022-06-09 08:56 UTC, kdb424 requested changes

2022-06-09 10:17 UTC, crazyiop commented on kmk/keys.py
> +                raise ValueError(f'Invalid key: {key}')
Moved that commit in a dedicated PR : https://github.com/KMKfw/kmk_firmware/pull/473

2022-06-09 11:03 UTC, xs5871 requested changes
There's a typo.

2022-06-09 11:03 UTC, xs5871 commented on docs/porting_to_kmk.md
> +to define both `keyboard.coord_mapping` and `keyboard.keymap`.
```suggestion
send its corresponding number. Use it after your pins and module definition
to define both `keyboard.coord_mapping` and `keyboard.keymap`.
```

2022-06-09 11:03 UTC, xs5871 commented on docs/porting_to_kmk.md
> +# of one side. Having this N too much will have no impact (maybe slower boot..)
```suggestion
# *2 for split keyboards, which will typically manage twice the number of keys
# of one side. Having this N too large will have no impact (maybe slower boot...)
```

2022-06-10 15:26 UTC, kdb424 approved these changes

2022-06-10 15:27 UTC, kdb424 commented
I'll let @xs5871 merge when he's happy, but otherwise, I think it's good on my part.

2022-06-11 19:27 UTC, xs5871 approved these changes

2022-06-11 19:27 UTC, merged