[doc:rgb] fix link to neopixel lib
KMKfw/kmk_firmware pull request #485
Opened 2022-06-21 22:23 UTC by crazyiop

The link is hardcoded to a commit from 2018-12-21 (version 3.3.5) while
we are currently at 6.3.3.

The rgb makes use of the fact that NeoPixel is a subclass of PixelBuf
but that was not true back then. Hence some people following the link in
the doc get a neopixel library incompatible with kmk.

2022-06-21 23:49 UTC, xs5871 requested changes

2022-06-21 23:49 UTC, xs5871 commented on docs/rgb.md
> +[here](https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/blob/main/neopixel.py)
```suggestion
This does require the [NeoPixel library from Adafruit](https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/blob/main/neopixel.py).
```

KMKPython is abandoned + improve bad practice "[here]" link

2022-06-22 23:50 UTC, xs5871 commented
Sorry for the unclear request: KMKPython is abandoned; please also remove the mention from the doc, since we're already revising it. I couldn't mark that line in the review, but I should have stated that more clearly.

2022-06-23 15:20 UTC, crazyiop commented
Ha sorry, its me who didn't get it. Fixed

But why couldn't you open a thread on that line ? It's not possible to comment on unchanged line in github ? (It's the first project I really use github PR... I'm only familiar with gitlab where that is possible)

2022-06-23 23:20 UTC, xs5871 commented
If it is possible, I couldn't figure it out.

2022-06-23 23:21 UTC, xs5871 approved these changes

2022-06-23 23:21 UTC, merged