Quickpin initial support
KMKfw/kmk_firmware pull request #608
Opened 2022-10-02 00:25 UTC by kdb424

This is intended to help ease the need for multiple kb.py by unifying pins per footprint. More footprints like feather/xiao and more can be added, but this is my initial attempt at creating the system being as careful to keep it light as I could. Additional support to ease transition from firmwares such as QMK have also been added.

2022-10-02 03:21 UTC, daysgobye approved these changes
This is awesome just what I was thinking. Would it add over head make it accessible with  dot notation instead on index? Just because it may be more maintainable then indexes.

2022-10-02 16:48 UTC, kdb424 commented
> This is awesome just what I was thinking. Would it add over head make it accessible with dot notation instead on index? Just because it may be more maintainable then indexes.

Dot notation would require a dict I believe. I would have to rethink the AVR pro micro support, and come up with names that may not always be the same for pins, but if you can come up with a sane system for that, I'm not opposed.

2022-10-04 01:15 UTC, klardotsh reviewed
As a general rule, images shouldn't usually go into Git directly: [Git LFS](https://git-lfs.github.com/) is ideally suited for that type of thing, and GitHub, Gitea, etc. all support it.

Not a blocker here since it's one 400K image. Not the end of the universe. Just not a precedent to continue setting (or clones of KMK will end up getting huge: once a binary blob is in git, the only way to get it out is to fully rewrite history using something like the [BFG](https://github.com/rtyley/bfg-repo-cleaner))

2022-10-04 01:18 UTC, klardotsh reviewed
Other note: we have `AttrDict` to allow dot notation, and while `1` is not a valid attribute name in Python, we already do hacks like `KC.N0` to plumb to the `0` key from the keys collection: while I'm not 100% sure it's cleaner than just `board.pins.P0_01` or whatever, we *can* use `AttrDict` or similar to achieve ergonomics like `pins[0] -> pins.P0`

2022-10-06 06:43 UTC, klardotsh approved these changes
Let's give @xs5871 last rights of refusal here since I don't actually have strong opinions on implementation here other than "this is a cool idea, and the syntax seems fine to me, but then, I work in code so...."

2022-10-07 07:34 UTC, xs5871 requested changes

2022-10-07 07:34 UTC, xs5871 commented on docs/quickpin.md
> +Quickpin helps devs quickly translate pinouts between boards of similar pinouts.
```suggestion
Quickpin helps devs quickly translate pinouts between boards of similar footprint.
```

2022-10-07 07:34 UTC, xs5871 commented on docs/quickpin.md
> +`kmk/quickpin/<footprint>/boardname.py`
```suggestion
`kmk/quickpin/<footprint>/boardname.py`.
```

2022-10-07 07:34 UTC, xs5871 commented on docs/quickpin.md
> +Pro Micro RP2040 shown as an example
```suggestion
Pro Micro RP2040 shown as an example:
```

2022-10-08 19:48 UTC, xs5871 approved these changes

2022-10-08 19:48 UTC, merged