Update layers.md
KMKfw/kmk_firmware pull request #664
Opened 2022-12-29 13:22 UTC by SivanSrimanPC

L87 to L90

1)the function declaration was missing the self argument, so added it.

2)i changed the color changing method call to just changing the hue parameter of the rgb object

2022-12-29 15:57 UTC, xs5871 commented
> 2)i changed the color changing method call to just changing the hue parameter of the rgb object... this works perfectly with the breathing animation

But it doesn't work with the static animation, because that one doesn't periodically update the LEDs.

2022-12-30 00:18 UTC, SivanSrimanPC commented
> > 2)i changed the color changing method call to just changing the hue parameter of the rgb object... this works perfectly with the breathing animation
> 
> But it doesn't work with the static animation, because that one doesn't periodically update the LEDs.

oh then i guess we can add this as a separate example for animations then
but for both cases the self argument needs to be passed

2023-01-07 19:12 UTC, xs5871 commented
Easy fix: leave the `rgb.set_hsv_fill(...)` line in. I agree with the rest of the PR.

2023-01-23 18:30 UTC, xs5871 requested changes

2023-01-23 18:30 UTC, xs5871 commented on docs/en/layers.md
> +			rgb.hue = self.last_top_layer
```suggestion
			rgb.set_hsv_fill(self.hues[self.last_top_layer], 255, 255)
			rgb.hue = self.hues[self.last_top_layer]
```

2023-02-12 17:29 UTC, xs5871 commented
There's a pending change request still open. Any updates?

2023-09-15 08:18 UTC, xs5871 approved these changes

2023-09-15 08:22 UTC, merged