Helix board support
KMKfw/kmk_firmware pull request #667
Opened 2023-01-02 03:27 UTC by lancewilhelm

Support for the Helix split ortholinear keyboard. Added two folders: one with a default keymap configuration as found in QMK and one for the custom keymap that I am currently using. Demonstrated OLED and RGB capability on a Sparkfun Pro Micro RP2040. 

In my keymap, I also adapted the code from the split module to flip OLED images and display different images based on the side of the split. Might be a nice feature to add into the OLED library down the road.

2023-01-02 22:59 UTC, xs5871 reviewed
Is there a way to deduplicate some of that code? We also stopped merging personal keymaps, because there's a lot of them, they're personal preference, and usually don't add meaningfull functionality.

2023-01-02 22:59 UTC, xs5871 commented on boards/helix/README.md
> +from kmk.quickpin.pro_micro.boardsource_blok import pinout as pins
missing code end of block "```".

2023-01-02 23:25 UTC, lancewilhelm commented on boards/helix/README.md
> +from kmk.quickpin.pro_micro.boardsource_blok import pinout as pins
fixed, thank you.

2023-01-02 23:25 UTC, lancewilhelm commented
Makes sense! I remove the personal keymap and then rolled up the default keymap into the root helix directory. Added the keymap layouts to the root README.md.

2023-01-07 19:09 UTC, xs5871 commented
Please check the linter logs for necessary changes. Once they're fixed, I'd ask you to squash commits for a less "polluted" history.

2023-01-08 22:06 UTC, xs5871 requested changes
One last nit pick, then we're good to go. Don't worry about the git/github stuff, happens everyone eventually. (easiest way would have been to rebase and force push, if you're ever in a similar situation.)

2023-01-08 22:06 UTC, xs5871 commented on boards/helix/main.py
> +# Layer support``
```suggestion
# Layer support
```

2023-01-08 22:17 UTC, lancewilhelm commented
It took me a couple of shots, but I think I figured out how to squash this time.  The ticks are now removed from `main.py`. Thanks.

2023-01-08 22:23 UTC, xs5871 approved these changes

2023-01-08 22:23 UTC, merged