Add Pico14 board from Bolt Industries
KMKfw/kmk_firmware pull request #671
Opened 2023-01-08 02:21 UTC by davigupta

2023-01-08 02:46 UTC, davigupta commented
kmk_firmware$ python3 -m unittest
...............................................................
----------------------------------------------------------------------
Ran 63 tests in 15.140s

OK

2023-01-08 21:09 UTC, xs5871 commented on boards/Pico14/README.md
> +kb.py is designed to work with the Pi Pico.
```suggestion
`kb.py` is designed to work with the Pi Pico.  
```

2023-01-08 21:09 UTC, xs5871 commented on boards/Pico14/README.md
> +Retailers
```suggestion
Retailers:
```

2023-01-08 21:09 UTC, xs5871 commented on boards/Pico14/kb.py
> +    _KMKKeyboard.extensions.append(leds)
This belongs into `main.py`.
Don't do code execution in the class header.

2023-01-08 21:09 UTC, xs5871 commented on boards/Pico14/main.py
> +    'INS',       ______,        'DEL',
Please use the `KC.xxx` pattern for the default configuration. Stringy keymaps are a niche application for special cases and not the recommended for default use.

2023-01-09 21:33 UTC, xs5871 requested changes

2023-01-09 21:33 UTC, xs5871 commented on boards/Pico14/kb.py
> +    leds = LED(led_pin=[board.GP27], val=0)
```suggestion
```

2023-01-09 21:33 UTC, xs5871 commented on boards/Pico14/main.py
> +
```suggestion
leds = LED(led_pin=[board.GP27], val=0)

```

2023-01-09 21:33 UTC, xs5871 commented on boards/Pico14/main.py
> +            Pico14.leds.set_brightness(100, leds=[0])
```suggestion
            leds.set_brightness(100, leds=[0])
```

2023-01-09 21:33 UTC, xs5871 commented on boards/Pico14/main.py
> +            Pico14.leds.set_brightness(0, leds=[0])
```suggestion
            leds.set_brightness(0, leds=[0])
```

2023-01-09 21:33 UTC, xs5871 commented on boards/Pico14/main.py
> +Pico14.extensions.append(Pico14.leds)
```suggestion
Pico14.extensions.append(leds)
```

2023-01-09 21:33 UTC, xs5871 commented on boards/Pico14/kb.py
> +    leds = LED(led_pin=[board.GP27], val=0)
This is still code execution in a class header.

2023-01-09 21:35 UTC, xs5871 commented
Forgot to mention: once done, please consider squashing the history.

2023-01-09 22:18 UTC, davigupta commented on boards/Pico14/main.py
> +            Pico14.leds.set_brightness(100, leds=[0])
update a new diff

2023-01-09 22:18 UTC, davigupta commented on boards/Pico14/main.py
> +            Pico14.leds.set_brightness(0, leds=[0])
updated a new diff

2023-01-09 22:18 UTC, davigupta commented on boards/Pico14/main.py
> +Pico14.extensions.append(Pico14.leds)
update a new diff

2023-01-10 18:42 UTC, davigupta reviewed
Addressed review comments.

2023-01-10 20:37 UTC, xs5871 commented
Yep, that works. Now kindly clean up the history by rebasing/squashing, so we don't have a bunch of merge/fix commits in our history.

2023-01-10 20:57 UTC, davigupta commented
Yes I squashed it. Pls see if you don’t see this in pull request.

Thanks

On Tue, Jan 10, 2023 at 12:38 PM xs5871 ***@***.***> wrote:

> Yep, that works. Now kindly clean up the history by rebasing/squashing, so
> we don't have a bunch of merge/fix commits in our history.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KMKfw/kmk_firmware/pull/671#issuecomment-1377817817>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABOCG5OOO42O5X7V2H5GD73WRXCCTANCNFSM6AAAAAATUJPQHM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-10 20:59 UTC, xs5871 commented
Nope, still shows up as 16 individual commits.

2023-01-10 21:29 UTC, davigupta commented
Ok I did squash only. Will do rebase and then squash.

Thanks

On Tue, Jan 10, 2023 at 12:59 PM xs5871 ***@***.***> wrote:

> Nope, still shows up as 16 individual commits.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KMKfw/kmk_firmware/pull/671#issuecomment-1377844539>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABOCG5LVTUVI5LTZTNB3QJDWRXESXANCNFSM6AAAAAATUJPQHM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-11 06:33 UTC, davigupta commented
Pls look at new pull request.

Thanks,
Davi

On 1/10/23 13:29, Davi Gupta wrote:
> Ok I did squash only. Will do rebase and then squash.
>
> Thanks
>
> On Tue, Jan 10, 2023 at 12:59 PM xs5871 ***@***.***> wrote:
>
>     Nope, still shows up as 16 individual commits.
>
>     —
>     Reply to this email directly, view it on GitHub
>     <https://github.com/KMKfw/kmk_firmware/pull/671#issuecomment-1377844539>,
>     or unsubscribe
>     <https://github.com/notifications/unsubscribe-auth/ABOCG5LVTUVI5LTZTNB3QJDWRXESXANCNFSM6AAAAAATUJPQHM>.
>     You are receiving this because you authored the thread.Message ID:
>     ***@***.***>
>

2023-01-11 06:34 UTC, davigupta commented
Pls look a new pull request:

https://github.com/KMKfw/kmk_firmware/pull/674

2023-01-16 18:44 UTC, davigupta commented
Thanks for the review. Can you pls take a look again?

https://github.com/KMKfw/kmk_firmware/pull/674

On 1/9/23 13:35, xs5871 wrote:
>
> Forgot to mention: once done, please consider squashing the history.
>
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/KMKfw/kmk_firmware/pull/671#issuecomment-1376355796>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABOCG5PC4WUIMDB5J6BFAPTWRSABXANCNFSM6AAAAAATUJPQHM>.
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>
>

2023-01-17 05:54 UTC, davigupta commented
Use old pull request 671 as requested.

2023-01-17 20:37 UTC, xs5871 approved these changes

2023-01-17 20:37 UTC, merged

2023-01-17 20:51 UTC, davigupta commented
Thanks!

On Tue, Jan 17, 2023 at 12:38 PM xs5871 ***@***.***> wrote:

> Merged #671 <https://github.com/KMKfw/kmk_firmware/pull/671> into master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KMKfw/kmk_firmware/pull/671#event-8249581684>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABOCG5J7IHYT3RKQ3BVJ24LWS37K3ANCNFSM6AAAAAATUJPQHM>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>