New OLED extension
KMKfw/kmk_firmware pull request #742
Opened 2023-03-15 09:59 UTC by regicidalplutophage

Continued from #726

Example config is now:
```
from kmk.extensions.oled import Oled, TextEntry, ImageEntry

oled_ext = Oled(entries=[
    TextEntry(text='my', x=128, y=0, x_anchor='R'),
    TextEntry(text='keyboard', x=128, y=10, x_anchor='R'),
    TextEntry(text='left', x=128, y=20, x_anchor='R', side='L'),
    TextEntry(text='right', x=128, y=20, x_anchor='R', side='R'),
    TextEntry(text='Layer: ', x=0, y=32, y_anchor='B'),
    TextEntry(text='BASE', x=40, y=32, y_anchor='B', layer=0),
    TextEntry(text='LOWER', x=40, y=32, y_anchor='B', layer=1),
    TextEntry(text='RAISE', x=40, y=32, y_anchor='B', layer=2),
    TextEntry(text='RGB', x=40, y=32, y_anchor='B', layer=3),
    TextEntry(text='SETTINGS', x=40, y=32, y_anchor='B', layer=4),
    TextEntry(text='0 1 2 3 4', x=0, y=4),
    TextEntry(text='0', x=0, y=4, inverted=True, layer=0),
    TextEntry(text='1', x=12, y=4, inverted=True, layer=1),
    TextEntry(text='2', x=24, y=4, inverted=True, layer=2),
    TextEntry(text='3', x=36, y=4, inverted=True, layer=3),
    TextEntry(text='4', x=48, y=4, inverted=True, layer=4),
],
    device_address=0x3C,
    width=128,
    height=32,
    flip=False,
    flip_left=False,
    flip_right=True,
    dim_time=10,
    off_time=30,
    powersave_dim_time=5,
    powersave_off_time=15,
    brightness=1,
    brightness_step=0.1,
)

keyboard.extensions.append(oled_ext)
```

2023-03-23 08:09 UTC, xs5871 commented
Let me know when you're ready for the next review.

2023-03-23 23:19 UTC, xs5871 requested changes

2023-03-24 01:08 UTC, regicidalplutophage commented on kmk/extensions/oled.py
> +        self.dim()
How do I best achieve that?

2023-03-24 01:17 UTC, regicidalplutophage commented on kmk/extensions/oled.py
> +                )
Right, I just realized it doesn't work the way I thought it does. The idea here was was to keep it at either 1/2 brightness or 0.1 but it becomes 0.1 on the next cycle regardless. I'm going to add ```dim_factor``` and ```powersave_dim_factor``` to the constructor.

2023-03-24 22:20 UTC, xs5871 approved these changes

2023-03-24 22:22 UTC, merged